'use strict';
const {spawn}=require('node:child_process'),{once}=require('node:events'),path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PR_REVIEW_PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const fixture=spawn(process.env.PYTHON||'python3',[path.join(__dirname,'../fixtures/triage_browser_fixture.py')],{stdio:['ignore','pipe','inherit']});
 let browser;
 try{
  const [chunk]=await once(fixture.stdout,'data');const url=chunk.toString().trim();
  browser=await chromium.launch({headless:true,channel:process.env.PR_REVIEW_BROWSER_CHANNEL||'chrome'});const page=await browser.newPage({viewport:{width:1360,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  // Rows open the side panel (#pr-drawer-body) with the full card.
  const panel=async row=>{await row.locator('td.row-updated,td.queue-status').first().click();await page.locator('#pr-drawer[open]').waitFor();return page.locator('#pr-drawer-body');};
  const closePanel=()=>page.click('#pr-drawer-close');
  await page.goto(url);await page.waitForSelector('.pr-row');
  assert.equal(await page.locator('#pr-list .pr-row').count(),5);
  assert.equal(await page.locator('.triage-summary img').count(),0);
  assert.equal(await page.locator('#triage-activity').isVisible(),false);
  await page.click('#filters-show');await page.selectOption('#triage-filter','quick');assert.equal(await page.locator('#pr-list .pr-row').count(),2);
  await page.reload();await page.waitForSelector('.pr-row');assert.equal(await page.locator('#pr-list .pr-row').count(),2);
  assert.equal(await page.inputValue('#triage-filter'),'quick');
  await page.click('#filters-show');await page.selectOption('#triage-filter','uncertain');assert.equal(await page.locator('#pr-list .pr-row').count(),1);
  await page.click('#clear-filters');assert.equal(await page.locator('#pr-list .pr-row').count(),5);
  await page.selectOption('#sort','effort');
  assert.deepEqual(await page.locator('#pr-list .pr-row').evaluateAll(els=>els.map(e=>e.dataset.pr.split('/').pop())),['1','5','2','3','4']);
  await page.click('#filters-dialog [data-close-dialog]');
  let first=await panel(page.locator('#pr-list .pr-row').first());await first.locator('.triage-details summary').click();
  await first.getByRole('button',{name:'Took more effort'}).click();
  await page.waitForFunction(()=>document.querySelector('#pr-drawer-body [data-triage-rating="too_low"]')?.getAttribute('aria-pressed')==='true');
  assert.equal(await first.locator('.triage-details').getAttribute('open'),'',"The panel keeps open sections when it re-renders");
  await page.reload();await page.waitForSelector('.pr-row');
  first=await panel(page.locator('#pr-list .pr-row').first());
  await first.locator('.triage-details summary').click();assert.equal(await first.getByRole('button',{name:'Took more effort'}).getAttribute('aria-pressed'),'true');
  await closePanel();
  await page.click('#my-reviews-tab');
  assert.deepEqual(await page.locator('#queue-list .queue-item').evaluateAll(els=>els.map(e=>e.dataset.queuePr.split('/').pop())),['3','1','6']);
  await page.click('#inbox-tab');
  await page.click('#settings-show');await page.check('#triage-enabled');await page.fill('#triage-limit','5');
  await page.getByRole('button',{name:'Save all settings',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#ai-save-state').textContent==='All settings saved');
  await page.reload();await page.waitForSelector('.pr-row');await page.click('#settings-show');assert.equal(await page.isChecked('#triage-enabled'),true);assert.equal(await page.inputValue('#triage-limit'),'5');
  await page.click('#settings [data-close-dialog]');
  const involved=page.locator('#pr-list [data-pr="https://github.com/example/repo/pull/3"]');
  assert.deepEqual(await involved.locator('.load-badge .load-bars i').evaluateAll(els=>els.map(e=>e.dataset.level)),['medium','high','high','unknown']);
  assert.equal(await involved.locator('.load-tip').count(),0,'The list shows the word and bars only');
  await involved.locator('.load-badge').click();
  const involvedPanel=page.locator('#pr-drawer-body');
  assert.equal(await involvedPanel.locator('.triage-details').getAttribute('open'),'');
  assert.match(await involvedPanel.locator('.load-parts').innerText(),/Three files <change>\./);
  await involvedPanel.locator('.load-badge').hover();
  assert.match(await involvedPanel.locator('.load-tip').innerText(),/Review load: High[\s\S]*Required context\s*High/);
  await closePanel();
  const outdatedRow=page.locator('#pr-list [data-pr="https://github.com/example/repo/pull/5"]');
  assert.match(await outdatedRow.locator('.load-badge').getAttribute('class'),/load-low.*is-outdated/);
  assert.match(await outdatedRow.locator('.load-badge').getAttribute('aria-label'),/Review load Low, outdated/);
  const outdated=await panel(outdatedRow);
  assert.equal(await outdated.locator('.load-tip').isVisible(),false);
  await outdated.locator('.load-badge').hover();assert.match(await outdated.locator('.load-tip').innerText(),/older commit/);
  await outdated.locator('.triage-details summary').click();
  assert.equal(await outdated.locator('[data-triage-rating]').first().isDisabled(),true);
  let rerunBody;
  await page.route('**/triage-reestimate',async route=>{rerunBody=route.request().postDataJSON();await route.fulfill({json:{started:true}});});
  await outdated.getByRole('button',{name:'Re-estimate',exact:true}).click();
  await page.waitForFunction(()=>!triageStarting);
  assert.deepEqual(rerunBody,{url:'https://github.com/example/repo/pull/5',estimate_id:'5'});
  await closePanel();
  await page.click('#my-reviews-tab');
  const personal=await panel(page.locator('#queue-list [data-queue-pr="https://github.com/example/repo/pull/6"]'));
  assert.equal(await personal.locator('.queue-tools').getAttribute('open'),'');
  await personal.locator('.triage-details summary').click();
  await personal.getByRole('button',{name:'Estimate review load',exact:true}).click();
  await page.waitForFunction(()=>!triageStarting);
  assert.deepEqual(rerunBody,{url:'https://github.com/example/repo/pull/6',estimate_id:''});
  await closePanel();
  await page.click('#inbox-tab');
  await page.route('**/api/state',async route=>{const response=await route.fetch();const body=await response.json();const draft=body.prs.find(p=>p.url.endsWith('/1'));draft.is_draft=true;draft.triage={status:'not_estimated',can_reestimate:true};await route.fulfill({response,json:body});});
  await page.evaluate(()=>loadState());
  const draft=await panel(page.locator('#pr-list [data-pr="https://github.com/example/repo/pull/1"]'));
  if(await draft.locator('.triage-details').getAttribute('open')===null)await draft.locator('.triage-details summary').click();
  assert.match(await draft.locator('.triage-summary').textContent(),/Draft/);
  await draft.getByRole('button',{name:'Estimate review load',exact:true}).click();
  await page.waitForFunction(()=>!triageStarting);
  assert.deepEqual(rerunBody,{url:'https://github.com/example/repo/pull/1',estimate_id:''});
  await closePanel();
  await page.unroute('**/api/state');
  // Mock polling transitions without triggering model work.
  let progressStatus={state:'running',started_at:new Date().toISOString(),target:5,processed:2,current_url:'https://github.com/example/repo/pull/3',phase:'estimating'},progressCalls=1,progressWaiting=9,progressEnabled=true;
  await page.route('**/api/state',async route=>{const response=await route.fetch();const body=await response.json();body.triage.status=progressStatus;body.triage.config.enabled=progressEnabled;body.triage.counts={eligible:15,estimated:5,uncertain:2,waiting:progressWaiting,active:1,retrying_later:0};body.triage.budget={date:new Date().toISOString().slice(0,10),calls:progressCalls};await route.fulfill({response,json:body});});
  await page.evaluate(()=>loadState());
  assert.match(await page.locator('#triage-progress-title').textContent(),/2 of 5 processed/);
  assert.equal(await page.locator('#triage-progress-bar').getAttribute('value'),'2');
  assert.equal(await page.locator('#triage-progress-current a').textContent(),'example/repo #3');
  assert.equal(await page.locator('#triage-progress-run').isDisabled(),true);
  assert.equal(await page.locator('[data-triage-reestimate]:enabled').count(),0);
  await page.click('#my-reviews-tab');assert.equal(await page.locator('#triage-activity').isVisible(),true);await page.click('#inbox-tab');
  assert.equal(await page.locator('#triage-progress').isVisible(),false);
  assert.match(await page.locator('#triage-activity-title').textContent(),/2 of 5 processed/);
  assert.equal(await page.locator('#triage-progress-run').isVisible(),false);
  await page.getByRole('button',{name:'Triage details',exact:true}).click();
  assert.equal(await page.locator('#triage-progress').isVisible(),true);
  assert.equal(await page.locator('#triage-progress-title').evaluate(el=>el===document.activeElement),true);
  assert.match(await page.locator('#triage-progress-counts').textContent(),/1\/5 model calls/);
  await page.click('#activity-dialog [data-close-dialog]');
  progressStatus={state:'idle',finished_at:new Date().toISOString(),processed:2,outcome:'failed',message:'Provider unavailable. Try again later.'};
  await page.evaluate(()=>loadState());assert.equal(await page.locator('#triage-progress-title').textContent(),'Review load estimates stopped');assert.match(await page.locator('#triage-activity-message').textContent(),/Provider unavailable/);
  assert.equal(await page.locator('#triage-progress-run').isVisible(),true);
  await page.route('**/triage-run',async route=>{await new Promise(resolve=>setTimeout(resolve,500));progressStatus={state:'starting',started_at:new Date().toISOString()};await route.fulfill({json:{started:true}});});
  await page.click('#triage-progress-run');assert.match(await page.locator('#triage-activity-title').textContent(),/Starting/);assert.equal(await page.locator('#triage-progress-run').isDisabled(),true);
  await page.waitForTimeout(600);
  progressStatus={state:'idle',finished_at:new Date().toISOString(),processed:5,uncertain:2,outcome:'batch_limit'};await page.evaluate(()=>loadState());assert.match(await page.locator('#triage-progress-title').textContent(),/5 PRs processed/);
  assert.equal(await page.locator('#triage-activity').isVisible(),false);
  await page.click('#activity-show');assert.equal(await page.locator('#triage-progress').isVisible(),true);assert.equal(await page.locator('#triage-run').isEnabled(),true);await page.click('#activity-dialog [data-close-dialog]');
  progressCalls=5;await page.evaluate(()=>loadState());assert.equal(await page.locator('#triage-progress-title').textContent(),'Daily triage limit reached');assert.equal(await page.locator('#triage-progress-run').isDisabled(),true);
  assert.equal(await page.locator('#triage-activity').isVisible(),true);assert.equal(await page.locator('#triage-progress-run').isVisible(),false);
  progressWaiting=0;await page.evaluate(()=>loadState());assert.equal(await page.locator('#triage-activity').isVisible(),false);
  progressWaiting=9;progressCalls=1;progressStatus={state:'idle',outcome:'interrupted',message:'Previous run interrupted.'};await page.evaluate(()=>loadState());assert.match(await page.locator('#triage-activity-message').textContent(),/interrupted/);
  progressEnabled=false;await page.evaluate(()=>loadState());assert.equal(await page.locator('#triage-activity').isVisible(),false);progressEnabled=true;
  progressCalls=1;progressStatus={state:'running',started_at:new Date().toISOString(),target:5,processed:2,current_url:'https://github.com/example/repo/pull/3',phase:'estimating'};await page.evaluate(()=>loadState());
  const output=process.env.TRIAGE_BROWSER_OUTPUT||'/tmp/pr-triage-browser';fs.mkdirSync(output,{recursive:true});
  for(const theme of ['light','dark'])for(const width of [1360,390,320]){
   await page.click('#settings-show');await page.click('[data-settings-panel="appearance-settings"]');await page.selectOption('#theme',theme);await page.click('#settings [data-close-dialog]');await page.setViewportSize({width,height:1000});
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow ${theme}/${width}`);
   await page.screenshot({path:path.join(output,`${theme}-${width}.png`),fullPage:true});
   await page.click('#settings-show');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Settings overflow ${theme}/${width}`);await page.screenshot({path:path.join(output,`settings-${theme}-${width}.png`),fullPage:true});await page.click('#settings [data-close-dialog]');
  }
  progressStatus={state:'idle',finished_at:new Date().toISOString(),processed:5,outcome:'caught_up'};progressWaiting=0;await page.evaluate(()=>loadState());
  await page.setViewportSize({width:1360,height:1000});await page.click('#settings-show');await page.click('[data-settings-panel="appearance-settings"]');await page.selectOption('#theme','light');await page.click('#settings [data-close-dialog]');await page.screenshot({path:path.join(output,'completed-light.png'),fullPage:true});
  assert.equal(await page.locator('#triage-activity').isVisible(),false);
  assert.deepEqual(errors,[]);console.log('Triage browser checks passed: filters, sort, feedback, persistence, settings, queue order, escaping, and 320/390/1360px light/dark layouts.');
 }finally{if(browser)await browser.close();fixture.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exitCode=1;});
