"""Provider-neutral request/event boundary. No fallback between providers."""
from dataclasses import dataclass, field
import re
from typing import Callable

@dataclass
class Request:
    mode: str
    cwd: str
    prompt: str
    model: str = ''
    effort: str = ''
    instructions: str = ''
    session_id: str = ''
    schema: dict | None = None
    context: dict = field(default_factory=dict)

@dataclass
class Callbacks:
    emit: Callable = lambda kind, text: None
    session: Callable = lambda session_id: None
    tool: Callable = lambda details: None
    draft: Callable = lambda text: None

class ProviderError(RuntimeError):
    """Safe, user-facing failure generated by an adapter, never raw SDK output."""


def sources(answer):
    result = []
    for title, url in re.findall(r'\[([^]\n]+)\]\((https?://[^\s)]+)\)', answer):
        if url not in {source['url'] for source in result}:
            result.append({'title': title, 'url': url})
    return result[:12]


def create(provider):
    if provider == 'codex':
        from provider_codex import Session
    elif provider == 'claude':
        from provider_claude import Session
    elif provider == 'openai':
        from provider_openai import Session
    else:
        raise ValueError('Unknown AI provider.')
    return Session()
